name: Generate Faker Data

on:
  # schedule:
  #   - cron: '0 */6 * * *'  # Every 8 hours
  workflow_dispatch:  # Manual trigger

jobs:
  generate-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install faker

    - name: Run Faker Data Generator
      run: python generate_faker_data.py

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name '${{ secrets.GIT_USER }}'
        git config --global user.email '${{ secrets.GIT_MAIL }}'
        commit_message=$(cat commit_message.txt)
        git add .
        git commit -m "$commit_message" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
